version: "3"

services:
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  nodeapp1:
    image: nodeapp
    environment:
      - ID=1111
  nodeapp2:
    image: nodeapp
    environment:
      - ID=2222
  nodeapp3:
    image: nodeapp
    environment:
      - ID=3333
  nodeapp5:
    image: nodeapp
    environment:
      - ID=5555
  nodeapp6:
    image: nodeapp
    environment:
      - ID=6666
